# ---

# controller_workflows:
#   # WorkFlow simple
#   - name: "{{ aap_naming_workflows }}-{{ aap_objects_suffix_description }}-simple" # to modify but keep {{ aap_naming_workflows }}
#     description: a basic workflow
#     extra_vars: ""
#     allow_simultaneous: false
#     inventory: "{{ aap_naming_inventories }}-{{ aap_objects_suffix_description }}" # to modify but inventory must exist
#     limit:
#     scm_branch:
#     ask_inventory_on_launch: false
#     ask_scm_branch_on_launch: false
#     ask_limit_on_launch: false
#     ask_skip_tags_on_launch: false
#     ask_tags_on_launch: false
#     extra_data: ""
#     ask_variables_on_launch: false
#     webhook_service: ""
#     webhook_credential:
#     organization:
#       name: "{{ user_organizations }}"
#     workflow_nodes:
#       - identifier: node001
#         unified_job_template:
#           name: "{{ aap_naming_templates }}-{{ aap_objects_suffix_description }}" # to modify
#           type: job_template
#           organization:
#             name: "{{ user_organizations }}"
#     destroy_current_nodes: true
#     state: present
# # WorkFlow complex
# # - name: "{{ aap_naming_workflows }}-{{ aap_objects_suffix_description }}-complex" #to modify but keep {{ aap_naming_workflows }}
# #   description: a complex workflow
# #   extra_vars: ''
# #   #survey_enabled: true
# #   allow_simultaneous: false
# #   inventory: "{{ aap_naming_inventories }}-{{ aap_objects_suffix_description }}" #to modify but inventory must exist
# #   limit:
# #   scm_branch:
# #   ask_inventory_on_launch: false
# #   ask_scm_branch_on_launch: false
# #   ask_limit_on_launch: false
# #   ask_skip_tags_on_launch: false
# #   ask_tags_on_launch: false
# #   extra_data: ""
# #   ask_variables_on_launch: false
# #   webhook_service: ''
# #   webhook_credential:
# #   organization:
# #     name: "{{ user_organizations }}"
# #   workflow_nodes:
# #   - identifier: "node001"
# #     unified_job_template:
# #       name: "{{ aap_naming_templates }}-{{ aap_objects_suffix_description }}" #to modify
# #       type: job_template
# #       organization:
# #         name: "{{ user_organizations }}"
# #     related:
# #       success_nodes:
# #       - identifier: "node002"
# #       failure_nodes: []
# #       always_nodes: []
# #   - identifier: "node002"
# #     unified_job_template:
# #       name: "{{ aap_naming_templates }}-{{ aap_objects_suffix_description }}" #to modify
# #       type: job_template
# #       organization:
# #         name: "{{ user_organizations }}"
# #     related:
# #       success_nodes:
# #       - identifier: "node003"
# #       failure_nodes:
# #       - identifier: "node005"
# #       always_nodes: []
# #   - identifier: "node003"
# #     unified_job_template:
# #       name: "{{ aap_naming_templates }}-{{ aap_objects_suffix_description }}" #to modify
# #       type: job_template
# #       organization:
# #         name: "{{ user_organizations }}"
# #   - identifier: "node004"
# #     unified_job_template:
# #       name: "{{ aap_naming_templates }}-{{ aap_objects_suffix_description }}" #to modify
# #       type: job_template
# #       organization:
# #         name: "{{ user_organizations }}"
# #   - identifier: "node005"
# #     unified_job_template:
# #       name: "{{ aap_naming_templates }}-{{ aap_objects_suffix_description }}" #to modify
# #       type: job_template
# #       organization:
# #         name: "{{ user_organizations }}"
# #   survey_spec:
# #     description: Generic demo Survey
# #     name: Generic demo Survey
# #     spec:
# #     - choices: ''
# #       default: ''
# #       max: 1024
# #       min: 0
# #       new_question: true
# #       question_description: textearea variable
# #       question_name: What is your textearea variable
# #       required: true
# #       type: textarea
# #       variable: your_textarea
# #     - choices: |-
# #         yes
# #         no
# #         maybe
# #         I dont know
# #       default: 'yes'
# #       max: 0
# #       min: 0
# #       new_question: true
# #       question_description: Single selection list
# #       question_name: Choose yes, no, maybe, I dont know
# #       required: true
# #       type: multiplechoice
# #       variable: single_selection
# #     - choices: |-
# #         Hello
# #         World
# #         Goodbye
# #       default: ''
# #       max: 0
# #       min: 0
# #       new_question: true
# #       question_description: Multiple selection list
# #       question_name: 'Select answers:'
# #       required: true
# #       type: multiselect
# #       variable: multiple_selection
# #     - choices: ''
# #       default: ''
# #       max: 1024
# #       min: 0
# #       new_question: true
# #       question_description: ''
# #       question_name: password
# #       required: true
# #       type: password
# #       variable: password
# #   destroy_current_nodes: true
# #   state: present
